site_name: DITA-OT Watermark Plug-in
repo_url: 'https://github.com/jason-fox/fox.jason.watermark'
repo_name: GitHub
pages:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
theme: readthedocs
extra_css:
  - 'https://jason-fox.github.io/fox.jason.watermark/dita.css'
